-- Sales Analytics Dashboard Database
CREATE DATABASE sales_analytics;
USE sales_analytics;
-- Customers Table
CREATE TABLE customers(
customer_id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
phone_number VARCHAR(20) NOT NULL UNIQUE,
gender ENUM('MALE','FEMALE','OTHER'),
city VARCHAR(100) NOT NULL,
country VARCHAR(150) NOT NULL,
join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Products Table
CREATE TABLE products(
product_id INT AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(150) NOT NULL,
category VARCHAR(100) NOT NULL,
brand VARCHAR(100) NOT NULL,
price INT DEFAULT 0,
stock_quantity INT DEFAULT 0
);
-- Region Table
CREATE TABLE regions(
region_id INT AUTO_INCREMENT PRIMARY KEY,
region_name VARCHAR(100) NOT NULL,
country  VARCHAR(100) NOT NULL,
manager_name VARCHAR(100) NOT NULL
);
-- Employee Table
CREATE TABLE employees(
employee_id INT AUTO_INCREMENT PRIMARY KEY,
employee_name VARCHAR(100) NOT NULL,
department VARCHAR(100) NOT NULL,
salary INT,
hire_date DATE,
region_id INT,
FOREIGN KEY (region_id) REFERENCES regions(region_id)
);
-- Orders Table (MAIN)
CREATE TABLE orders(
order_id INT AUTO_INCREMENT PRIMARY KEY,
customer_id INT,
product_id INT,
employee_id INT,
quantity INT,
unit_price INT DEFAULT 0,
discount INT,
order_date DATE,
payment_method VARCHAR(100),
order_status ENUM('Completed','Pending','Cancelled'),
CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(product_id),
CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);

-- SALES ANALYTICS DASHBOARD - COMPLETE ANALYSIS

-- Database: sales_analytics
-- Tables: customers, products, orders, employees, regions

-- 1. CUSTOMER-WISE TOTAL ORDERS & QUANTITY ANALYSIS
-- Total orders placed and total quantity purchased 
-- by each customer for completed transactions


SELECT 
    c.user_name as customer_name,
    SUM(o.quantity) as total_quantity,
    COUNT(o.order_id) as total_orders
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.user_name
ORDER BY total_orders DESC;

-- 2. PRODUCT-WISE REVENUE PERFORMANCE (AFTER DISCOUNT)
-- Ranking products based on total revenue generated, 
-- with discount adjustments applied

SELECT 
    p.product_name,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) as total_revenue
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

-- 3. 30-DAY INACTIVE CUSTOMER ANALYSIS
-- Identifying customers with no orders in the last 30 days, 
-- showing last order date and days since last purchase

SELECT 
    c.user_name,
    c.email,
    MAX(o.order_date) as last_order_date,
    DATEDIFF(CURDATE(), MAX(o.order_date)) AS days_since_order
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.user_name, c.email
HAVING days_since_order > 30
ORDER BY days_since_order DESC;

-- 4. EMPLOYEE MONTHLY PERFORMANCE DASHBOARD
-- Monthly breakdown of orders handled and revenue 
-- generated by each employee

SELECT 
    e.employee_name,
    MONTHNAME(o.order_date) as month_name,
    COUNT(o.order_id) as total_orders,
    SUM(o.quantity * o.unit_price * (1 - o.discount/100)) as total_revenue
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name, MONTHNAME(o.order_date), MONTH(o.order_date)
ORDER BY MONTH(o.order_date), e.employee_name;

-- 5. CATEGORY-WISE AVERAGE ORDER VALUE (AOV) ANALYSIS
-- Calculating Average Order Value (AOV) per product category
-- AOV = Total Revenue / Total Number of Orders


SELECT 
    p.category,
    COUNT(o.order_id) as total_orders,
    SUM(o.quantity * o.unit_price * (1 - o.discount/100)) as total_revenue,
    ROUND(
        SUM(o.quantity * o.unit_price * (1 - o.discount/100)) / 
        COUNT(o.order_id), 
        2
    ) as AOV
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY p.category
ORDER BY AOV DESC;
-- View of employees perfomence monthly by department
CREATE VIEW employee_performance_by_department AS
SELECT e.department, MONTHNAME(o.order_date) AS month_name, 
COUNT(distinct e.employee_id) AS total_employees,
COUNT(o.order_id) AS total_orders, 
SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenu,
ROUND(SUM(o.unit_price * o.quantity * (1 - o.discount/100))/count(distinct e.employee_id), 2) AS avg_revenu 
FROM orders o INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.department, MONTHNAME(o.order_date);
SELECT * FROM employee_performance_by_department;

-- Total Orders and Revenu by Department..
SELECT e.department, count(o.order_id) AS total_orders,
SUM(o.unit_price * o.quantity * (1-o.discount/100)) AS total_revenu FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed' GROUP BY e.department;
-- ----------------------------------------------
-- Total Orders and Revenu By Department Monthly
SELECT e.department, count(o.order_id) AS total_orders,
SUM(o.unit_price * o.quantity * (1-o.discount/100)) AS total_revenu,
MONTHNAME(o.order_date) AS Month_of_Order FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed' GROUP BY e.department, MONTHNAME(o.order_date)
ORDER BY MONTHNAME(o.order_date) DESC;
-- Employees Monthly Sales 
SELECT e.employee_name,MONTHNAME(o.order_date) as Monthly_sales, count(o.order_id) AS total_orders,
SUM(o.unit_price * o.quantity * (1-o.discount/100)) AS total_revenu FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed' GROUP BY e.employee_name, MONTHNAME(o.order_date);
-- Employees With Salary difference from Average salary, below, above and equal to avg salary
-- by each department...
SELECT employee_name, department, salary,
AVG(salary) OVER(PARTITION BY department) AS avg_salary,
salary - AVG(salary) OVER(PARTITION BY department) AS salary_diff,
CASE
	WHEN salary > AVG(salary) OVER(PARTITION BY department) THEN 'YES' ELSE 'NO' 
	END AS above_avg_salary,
CASE
	WHEN salary < AVG(salary) OVER(PARTITION BY department) THEN 'YES' ELSE 'NO'
    END AS below_avg_salary,
CASE
	WHEN salary = AVG(salary) OVER(PARTITION BY department) THEN 'YES' ELSE 'NO'
    END AS equal_avg_salary
FROM employees;
-- Showing the top 2 highest paying employees by each department
WITH ranked_employees AS
(
    SELECT
        employee_name,
        department,
        salary,
        RANK() OVER(
            PARTITION BY department
            ORDER BY salary DESC
        ) AS rank_in_dept
    FROM employees
)

SELECT *
FROM ranked_employees
WHERE rank_in_dept <= 2;
-- END OF ANALYSIS

-- EXECUTIVE SUMMARY:
-- 1. Top customers identified with highest order volume
-- 2. Best performing products by revenue ranking
-- 3. Inactive customers flagged for re-engagement campaigns
-- 4. Employee performance tracked monthly
-- 5. Category-level AOV insights for pricing strategy-- =============================================
-- SALES ANALYTICS DASHBOARD
-- Complete Data Analysis & Reporting Solution
-- =============================================
-- Database: sales_analytics
-- Tables: customers, products, orders, employees, regions
-- =============================================

CREATE DATABASE sales_analytics;
USE sales_analytics;

-- =============================================
-- 1. CUSTOMERS TABLE
-- Stores customer demographic and contact information
-- =============================================
CREATE TABLE customers(
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    gender ENUM('MALE','FEMALE','OTHER'),
    city VARCHAR(100) NOT NULL,
    country VARCHAR(150) NOT NULL,
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================
-- 2. PRODUCTS TABLE
-- Product catalog with pricing and inventory
-- =============================================
CREATE TABLE products(
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    price INT DEFAULT 0,
    stock_quantity INT DEFAULT 0
);

-- =============================================
-- 3. REGIONS TABLE
-- Regional management and territories
-- =============================================
CREATE TABLE regions(
    region_id INT AUTO_INCREMENT PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    manager_name VARCHAR(100) NOT NULL
);

-- =============================================
-- 4. EMPLOYEES TABLE
-- Employee records linked to regions
-- =============================================
CREATE TABLE employees(
    employee_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    salary INT,
    hire_date DATE,
    region_id INT,
    FOREIGN KEY (region_id) REFERENCES regions(region_id)
);

-- =============================================
-- 5. ORDERS TABLE (MAIN)
-- Transaction records with complete audit trail
-- =============================================
CREATE TABLE orders(
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    employee_id INT,
    quantity INT,
    unit_price INT DEFAULT 0,
    discount INT,
    order_date DATE,
    payment_method VARCHAR(100),
    order_status ENUM('Completed','Pending','Cancelled'),
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);

-- =============================================
-- PERFORMANCE OPTIMIZATION INDEXES
-- =============================================
CREATE INDEX idx_orders_status ON orders(order_status);
CREATE INDEX idx_orders_date ON orders(order_date);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_product ON orders(product_id);
CREATE INDEX idx_orders_employee ON orders(employee_id);

-- =============================================
-- ANALYSIS QUERIES
-- =============================================

-- 1. CUSTOMER-WISE ORDER ANALYSIS
-- Total orders and quantity per customer
SELECT 
    c.user_name AS customer_name,
    SUM(o.quantity) AS total_quantity,
    COUNT(o.order_id) AS total_orders
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.user_name
ORDER BY total_orders DESC;

-- 2. PRODUCT REVENUE RANKING
-- Best performing products with discount adjustment
SELECT 
    p.product_name,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenue
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

-- 3. INACTIVE CUSTOMER IDENTIFICATION
-- Customers with no orders in last 30 days
SELECT 
    c.user_name,
    c.email,
    MAX(o.order_date) AS last_order_date,
    DATEDIFF(CURDATE(), MAX(o.order_date)) AS days_since_order
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.user_name, c.email
HAVING days_since_order > 30
ORDER BY days_since_order DESC;

-- 4. EMPLOYEE MONTHLY PERFORMANCE
-- Monthly orders and revenue per employee
SELECT 
    e.employee_name,
    MONTHNAME(o.order_date) AS month_name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.quantity * o.unit_price * (1 - o.discount/100)) AS total_revenue
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name, MONTHNAME(o.order_date), MONTH(o.order_date)
ORDER BY MONTH(o.order_date), e.employee_name;

-- 5. CATEGORY AOV ANALYSIS
-- Average Order Value by product category
SELECT 
    p.category,
    COUNT(o.order_id) AS total_orders,
    SUM(o.quantity * o.unit_price * (1 - o.discount/100)) AS total_revenue,
    ROUND(
        SUM(o.quantity * o.unit_price * (1 - o.discount/100)) / 
        COUNT(o.order_id), 
        2
    ) AS AOV
FROM orders o
INNER JOIN products p ON o.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY p.category
ORDER BY AOV DESC;

-- 6. DEPARTMENT PERFORMANCE SUMMARY
SELECT 
    e.department,
    COUNT(o.order_id) AS total_orders,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenue
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.department;

-- 7. DEPARTMENT MONTHLY PERFORMANCE
SELECT 
    e.department,
    MONTHNAME(o.order_date) AS month_name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenue
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.department, MONTHNAME(o.order_date)
ORDER BY MONTHNAME(o.order_date) DESC;

-- 8. EMPLOYEE MONTHLY SALES
SELECT 
    e.employee_name,
    MONTHNAME(o.order_date) AS month_name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenue
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_name, MONTHNAME(o.order_date);

-- =============================================
-- VIEWS
-- =============================================

-- Department Monthly Performance View
CREATE VIEW employee_performance_by_department AS
SELECT 
    e.department,
    MONTHNAME(o.order_date) AS month_name,
    COUNT(DISTINCT e.employee_id) AS total_employees,
    COUNT(o.order_id) AS total_orders,
    SUM(o.unit_price * o.quantity * (1 - o.discount/100)) AS total_revenue,
    ROUND(
        SUM(o.unit_price * o.quantity * (1 - o.discount/100)) / 
        COUNT(DISTINCT e.employee_id), 
        2
    ) AS avg_revenue_per_employee
FROM orders o
INNER JOIN employees e ON o.employee_id = e.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.department, MONTHNAME(o.order_date);

-- =============================================
-- WINDOW FUNCTIONS ANALYSIS
-- =============================================

-- 9. SALARY ANALYSIS BY DEPARTMENT
-- Compare each employee's salary against department average
SELECT 
    employee_name,
    department,
    salary,
    AVG(salary) OVER(PARTITION BY department) AS avg_salary,
    salary - AVG(salary) OVER(PARTITION BY department) AS salary_diff,
    CASE
        WHEN salary > AVG(salary) OVER(PARTITION BY department) THEN 'ABOVE'
        WHEN salary < AVG(salary) OVER(PARTITION BY department) THEN 'BELOW'
        ELSE 'EQUAL'
    END AS salary_status
FROM employees;

-- 10. TOP PERFORMERS BY DEPARTMENT
-- Top 2 highest paid employees in each department
WITH ranked_employees AS (
    SELECT
        employee_name,
        department,
        salary,
        RANK() OVER(
            PARTITION BY department
            ORDER BY salary DESC
        ) AS rank_in_dept
    FROM employees
)
SELECT *
FROM ranked_employees
WHERE rank_in_dept <= 2;

-- =============================================
-- EXECUTIVE SUMMARY
-- =============================================
-- 1. Top customers identified by order volume
-- 2. Best performing products ranked by revenue
-- 3. Inactive customers flagged for re-engagement
-- 4. Employee performance tracked monthly
-- 5. Category-level AOV insights for pricing
-- 6. Department-wise revenue distribution
-- 7. Salary analysis with department averages
-- 8. Top performers identified by department
-- =============================================